#pragma once

#define PLAYER_ACCELERATION 200.0f
#define PLAYER_ANGULAR_ACCELERATION M_PI_2
#define PLAYER_TOP_SPEED 200.0f

#define SHOT_TOP_SPEED 100.0f
#define PLAYER_SHOT_TOP_SPEED 300.0f
#define ENEMY_SHOT_TOP_SPEED 250.0f
#define SHOT_DAMAGE 10

#define BOAT_ACCELERATION 150.0f
#define BOAT_ANGULAR_ACCELERATION M_PI_2
#define BOAT_TOP_SPEED 150.0f

#define GUNBOAT_ACCELERATION 150.0f
#define GUNBOAT_ANGULAR_ACCELERATION M_PI
#define GUNBOAT_TOP_SPEED 150.0f

#define BOSS_ACCELERATION 150.0f
#define BOSS_ANGULAR_ACCELERATION M_PI_2
#define BOSS_TOP_SPEED 150.0f

#define GUN_TURRET_ACCELERATION 150.0f
#define GUN_TURRET_ANGULAR_ACCELERATION M_PI
#define GUN_TURRET_TOP_SPEED 150.0f

#define COLLISION_DAMAGE 10

#define CAMERA_MOVING_SPEED 15.0f
#define GAME_WORLD_EPS 0.002f